# Generated by Django 5.1.3 on 2026-04-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="purpose",
            field=models.CharField(default="register", max_length=20),
        ),
    ]
