# Generated by Django 5.1.3 on 2026-04-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_otpverification_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="issue_type",
            field=models.CharField(
                choices=[("task", "Task"), ("story", "Story"), ("bug", "Bug")],
                default="task",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("in_review", "In Review"),
                    ("testing", "Testing"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
