# Generated by Django 5.1.3 on 2026-05-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_task_issue_type_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
