# Generated by Django 5.1.3 on 2026-05-04 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_goal_is_active_goal_is_deleted_task_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
