# Generated by Django 5.1.3 on 2026-05-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="joinrequest",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="joinrequest",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="joinrequest",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="joinrequest",
            name="user",
        ),
        migrations.AddField(
            model_name="organization",
            name="organization_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="Invitation",
        ),
        migrations.DeleteModel(
            name="JoinRequest",
        ),
    ]
