# Generated by Django 5.1.3 on 2026-05-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted (Waiting Finalization)"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                    ("finalized", "Finalized"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
